console.log(Number.MAX_SAFE_INTEGER);
console.log(Number.NEGATIVE_INFINITY);
console.log(Number.POSITIVE_INFINITY);
console.log(Number.length);
console.log(Number.parseInt(5));
console.log(Number.parseInt('5'));
console.log(Number.parseInt('7.25'));
console.log('-----------------------')
console.log(Number.parseFloat(5));
console.log(Number.parseFloat('5'));
console.log(Number.parseFloat('7.25'));
console.log('------------------------')
console.log(parseInt(5));
console.log(parseInt('5'));
console.log(parseInt('7.25'));
console.log('------------------------')
console.log(parseFloat(5));
console.log(parseFloat('5'));
console.log(parseFloat('7.25'));